# Form implementation generated from reading ui file 'c:\Users\Public\Documents\GitHub\Project---UI-Communications\User Interface\WeatherApp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


