# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sign_upLwNOmU.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)
import nydec_pic_src_file_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QSize(1024, 600))
        MainWindow.setMaximumSize(QSize(1024, 600))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.UsernameInput = QLineEdit(self.centralwidget)
        self.UsernameInput.setObjectName(u"UsernameInput")
        self.UsernameInput.setGeometry(QRect(40, 200, 301, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsernameInput.sizePolicy().hasHeightForWidth())
        self.UsernameInput.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.UsernameInput.setFont(font)
        self.UsernameLabel = QLabel(self.centralwidget)
        self.UsernameLabel.setObjectName(u"UsernameLabel")
        self.UsernameLabel.setGeometry(QRect(40, 170, 111, 16))
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 160, 220, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        brush2 = QBrush(QColor(0, 160, 220, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.UsernameLabel.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.UsernameLabel.setFont(font1)
        self.UsernameLabel.setStyleSheet(u"color:rgb(0, 160, 220);\n"
"")
        self.PasswordLabel = QLabel(self.centralwidget)
        self.PasswordLabel.setObjectName(u"PasswordLabel")
        self.PasswordLabel.setGeometry(QRect(40, 280, 101, 16))
        self.PasswordLabel.setFont(font1)
        self.PasswordLabel.setStyleSheet(u"color:rgb(0, 160, 220);")
        self.PaswordInput = QLineEdit(self.centralwidget)
        self.PaswordInput.setObjectName(u"PaswordInput")
        self.PaswordInput.setGeometry(QRect(40, 310, 301, 31))
        self.PaswordInput.setFont(font)
        self.PaswordInput.setEchoMode(QLineEdit.Password)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 30, 141, 41))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI Variable Display Semib"])
        font2.setPointSize(22)
        font2.setBold(True)
        self.label.setFont(font2)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 90, 301, 16))
        font3 = QFont()
        font3.setFamilies([u"Cambria Math"])
        font3.setPointSize(12)
        font3.setItalic(False)
        self.label_2.setFont(font3)
        self.label_2.setStyleSheet(u"color:rgb(115, 115, 115);\n"
"")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(40, 390, 301, 41))
        palette2 = QPalette()
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush4 = QBrush(QColor(255, 255, 255, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.pushButton.setPalette(palette2)
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Variable Display Semib"])
        font4.setPointSize(13)
        font4.setBold(True)
        self.pushButton.setFont(font4)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"background-color:rgb(0, 160, 220);\n"
"color:white;\n"
"border-color:rgb(0, 167, 167)")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 490, 131, 21))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI Semibold"])
        font5.setPointSize(11)
        font5.setBold(True)
        self.label_3.setFont(font5)
        self.label_3.setStyleSheet(u"color:rgb(100, 100, 100);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(280, 490, 61, 21))
        self.label_4.setFont(font5)
        self.label_4.setStyleSheet(u"color:rgb(32, 197, 87)")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1024, 600))
        self.frame.setMinimumSize(QSize(1024, 600))
        self.frame.setMaximumSize(QSize(1024, 600))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.frame.setPalette(palette3)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(490, 20, 491, 431))
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame.raise_()
        self.UsernameInput.raise_()
        self.UsernameLabel.raise_()
        self.PasswordLabel.raise_()
        self.PaswordInput.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.UsernameInput.setText("")
        self.UsernameInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"example@email.com", None))
        self.UsernameLabel.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.PasswordLabel.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.PaswordInput.setInputMask("")
        self.PaswordInput.setText("")
        self.PaswordInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Password...", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sign In", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Hi there! Nice to see you again!", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Sign In", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Forgot Password?", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Sign Up", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Nydec_pic/Screenshot 2024-04-09 110121.png\"/></p></body></html>", None))
    # retranslateUi

